### ISSUE TITLE
Errors ignored in SFC docs when outside exported object

### ISSUE THREAD

**Issue by tony19** [vue-styleguidist/vue-styleguidist#177]
Errors inside an SFC's `<script>` tag but outside the exported object  (as shown in the example below) yields no error.

<pre>
### Demo

```vue
&lt;template&gt;
  &lt;div&gt;test&lt;/div&gt;
&lt;/template&gt;

&lt;script&gt;
const foo = require('/path/to/nonexistent/file');  &lt;-- no error
foo(); &lt;-- no error

export default {
  mounted() {
    foo(); <-- error seen in console and browser terminal (as expected)
  }
}
&lt;/script&gt;
```
</pre>

### Environment
 * `vue-styleguide`: 1.7.13 and 1.8.0
 * Node 10.5.0
 * macOS High Sierra 10.13.6

**Comment by elevatebart** [comment]
I believe this has been fixed. Can you try v3 ?

**Comment by tony19** [comment]
Not entirely fixed unfortunately. Here's the new behavior with v3.8.3:

 * `require('/path/to/nonexistent/file')` throws "module not found" error 👍
 * `nonexistent()` and `foo123` (syntax error) are still silently ignored :x:

**Comment by elevatebart** [comment]
2 is not an error, as it could be a call to a `window` variable. As an alternative solution, I suggest using eslint rules or typescript compilation.

Am I missing something?

**Comment by elevatebart** [comment]
```vue
<script>
foo123()                                            // what happens then?
foo123 bar()                                      // and then?
</script>
```

**Comment by tony19** [comment]
> 2 is not an error, as it could be a call to a window variable.

Hmm. If that window variable doesn't exist, it should be a `ReferenceErrror` at the very least (ideally a compile error). I would expect the behavior to be the same as it would be in a regular `.vue` file with regard to compile errors. Why would it be different?

For https://github.com/vue-styleguidist/vue-styleguidist/issues/177#issuecomment-471319439, no errors:

```vue
<script>
foo123()                                          // ❌ignored
foo123 bar()                                      // ❌ignored
</script>
```
