### ISSUE TITLE
Two problems about slot comment on docs

### ISSUE THREAD

**Issue by Knovour** [vue-styleguidist/vue-styleguidist#45]
1. If a component don't have props, the slot comment will be ignore.
2. If template lang is `pug`, the slot comment won't show on style guide, both `//-` and `//`.

<details open>
<summary>Normal</summary>
<img src="https://user-images.githubusercontent.com/893846/32928707-5d7741ba-cb8e-11e7-8d5d-78cded73ee29.png" alt="code">
<img src="https://user-images.githubusercontent.com/893846/32928709-61a76dc8-cb8e-11e7-9c19-801c6ba3d487.png" alt="result">
</details>
<br>
<details>
<summary>Without props</summary>
<img src="https://user-images.githubusercontent.com/893846/32928723-775aa6bc-cb8e-11e7-997c-383582c394f1.png" alt="code">
<img src="https://user-images.githubusercontent.com/893846/32928728-7c39f2a0-cb8e-11e7-9abb-d510bfa37df9.png" alt="result">
</details>
<br>
<details>
<summary>With `lang="pug"`</summary>
<img src="https://user-images.githubusercontent.com/893846/32928770-a71c9720-cb8e-11e7-9191-b2382011769e.png" alt="code">
<img src="https://user-images.githubusercontent.com/893846/32928773-acefb5f6-cb8e-11e7-9127-f3965703a818.png" alt="result">
</details>

**Comment by rafaesc** [comment]
Hi @Knovour.

The problem is already solved in the version 1.3.5

**Comment by Knovour** [comment]
Thank you, the normal template is ok now, but pug support still the same.

**Comment by rafaesc** [comment]
Hi @Knovour,

Yes, I hadn't seen it. I already added the issue here: 
https://github.com/vue-styleguidist/vue-docgen-api/issues/13
